language: erlang
script: sudo DOCKER_PROJECT_COMMAND='make dialyze eunit EUNIT_OPTS=verbose' ./run-docker.sh
notifications:
  email:
    on_success: never
    on_failure: always
otp_release:
  - 19.0
sudo: required
services:
  - docker

